CREATE TABLE IF NOT EXISTS "companies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"Rank" bigint,
	"Company" text,
	"Ticker" text,
	"Sector" text,
	"Industry" text,
	"Profitable" text,
	"Founder_is_CEO" text,
	"FemaleCEO" text,
	"Growth_in_Jobs" text,
	"Change_in_Rank" double precision,
	"Gained_in_Rank" text,
	"Dropped_in_Rank" text,
	"Newcomer_to_the_Fortune500" text,
	"Global500" text,
	"Worlds_Most_Admired_Companies" text,
	"Best_Companies_to_Work_For" text,
	"Number_of_employees" bigint,
	"MarketCap_March28_M" double precision,
	"Revenues_M" double precision,
	"RevenuePercentChange" double precision,
	"Profits_M" double precision,
	"ProfitsPercentChange" double precision,
	"Assets_M" double precision,
	"CEO" text,
	"Country" text,
	"HeadquartersCity" text,
	"HeadquartersState" text,
	"Website" text,
	"CompanyType" text,
	"Footnote" text,
	"MarketCap_Updated_M" double precision,
	"Updated" text
);
